name: Elixir

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 23.1
          elixir-version: 1.11.0

      - name: Install Dependencies
        run: mix deps.get

      - name: Build and check for warnings 
        run: mix compile --force --warnings-as-errors
    
      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

      - name: Run Tests with Coverage
        run: mix coveralls.json
      
      - name: Upload Coverage
        run: bash <(curl -s https://codecov.io/bash)
